#############################################################################
# File name:  Makefile
# Author:     chadd williams
# Date:       June 6, 2022
# Class:      CS300
# Assignment: Airport, et al.
# Purpose:    Practice with Data structures!
#############################################################################

#### DO NOT EDIT THIS FILE ####

.PHONY: ListADT PriorityQueueADT QueueADT Airport

all: Airport

ListADT:
	cd $@; make

PriorityQueueADT: ListADT
	cd $@; make

QueueADT: PriorityQueueADT
	cd $@; make

Airport: QueueADT
	cd $@; make

clean:
	cd ListADT; make clean
	cd PriorityQueueADT; make clean
	cd QueueADT; make clean
	cd Airport; make clean

#### DO NOT EDIT THIS FILE ####
